version: '3'
services:
  backend:
    image: giltayar/realworld-frontend-testing
    environment:
      PORT: 80
      MONGODB_URI: db:27017
      SECRET: "shhhh"
    depends_on:
        - db

  db:
    image: mongo:3.4
    expose:
      - 27017
